# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62b910096f04c005e493ef7817b757f1bbebb54c8d4add9f209c07ddb65c553cb04269fdcd32fa5b610c7e44c3b722a34e3f6616b9ade971c203c8fc2b7a6277

test:
  secret_key_base: dea2bac69be69b103a3785d7c4c2cf45f99f3141af2d4c622dd36cebb2b85a9449364834aad96c70b7602569ebbe353e9fc273062e6380993f8c16f2b364b528

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
